---


- hosts: all
  gather_facts: no



  tasks:
  - name: Root FS usage
    shell: df -hT {{ FS_MOUNTPOINT }} | awk ' {print $5 } ' | grep -v Use
    register: dfroot


  - debug:
      msg: "System {{ inventory_hostname }}'s root FS utilization is {{ dfroot.stdout }}"
    
